name             'horta-hell'
maintainer       'Friedrich von Never'
maintainer_email 'friedrich@fornever.me'
license          'all_rights'
description      'Installs/Configures horta-hell'
long_description 'Installs/Configures horta-hell'
version          '0.1.0'
